%% optimization criterion: joints is vector of joint angles
function [score, gradient] = criterionGradient(joints,target,linkLengths,min_roll,min_pitch,min_yaw,max_roll,max_pitch,max_yaw)
    global h_axes link1 link2 link3 link4 link5 link6 link7 link8 link9 link10 targetVisual;
    
    %reshape
    joints = reshape(joints,[length(linkLengths) 3]);

    %forward kinematics
    [pose, positions] = fk(joints,linkLengths,target);
        
    %joints near limit their limits cost
    for i=1:length(joints)
        roll_average(i) = mean([min_roll(i) max_roll(i)]);
        pitch_average(i) = mean([min_pitch(i),max_pitch(i)]);
        yaw_average(i) = mean([min_yaw(i),max_yaw(i)]);
        difference_matrix(i,:) = [abs(joints(i,1)-roll_average(i)), abs(joints(i,2)-pitch_average(i)), abs(joints(i,3)-yaw_average(i))];
    end
    joint_limit_cost = 0.25 * norm(difference_matrix);
    
    %final pose cost
    final_pose_cost = 5 * norm(pose(1:7)-target(1:7));
    
    %total cost
    score = final_pose_cost + joint_limit_cost;
    
    %gradient stuff
    joints = joints(:);
    gradient = [];
    dtheta = 0.01;
    for i = 1:length(joints)
        joints2 = joints;
        dfdtheta1 = criterion(joints,target,linkLengths,min_roll,min_pitch,min_yaw,max_roll,max_pitch,max_yaw);
        joints2(i) = joints(i) + dtheta;
        dfdtheta2 = criterion(joints2,target,linkLengths,min_roll,min_pitch,min_yaw,max_roll,max_pitch,max_yaw);
        gradient(i,1) = (dfdtheta2 - dfdtheta1)/dtheta;
    end
    
    %draw all links
    if length(linkLengths)==1
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
    elseif length(linkLengths)==2
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
        set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                                   'Ydata',[positions(2,1) positions(2,2)], ...
                                   'Zdata',[positions(3,1) positions(3,2)],'visible','on');
    elseif length(linkLengths)==3
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
        set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                                   'Ydata',[positions(2,1) positions(2,2)], ...
                                   'Zdata',[positions(3,1) positions(3,2)],'visible','on');    
        set(link3,'Parent',h_axes, 'Xdata',[positions(1,2) positions(1,3)], ...
                                   'Ydata',[positions(2,2) positions(2,3)], ...
                                   'Zdata',[positions(3,2) positions(3,3)],'visible','on');
    elseif length(linkLengths)==4
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
        set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                                   'Ydata',[positions(2,1) positions(2,2)], ...
                                   'Zdata',[positions(3,1) positions(3,2)],'visible','on');    
        set(link3,'Parent',h_axes, 'Xdata',[positions(1,2) positions(1,3)], ...
                                   'Ydata',[positions(2,2) positions(2,3)], ...
                                   'Zdata',[positions(3,2) positions(3,3)],'visible','on');
        set(link4,'Parent',h_axes, 'Xdata',[positions(1,3) positions(1,4)], ...
                                   'Ydata',[positions(2,3) positions(2,4)], ...
                                   'Zdata',[positions(3,3) positions(3,4)],'visible','on');
    elseif length(linkLengths)==5
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
        set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                                   'Ydata',[positions(2,1) positions(2,2)], ...
                                   'Zdata',[positions(3,1) positions(3,2)],'visible','on');    
        set(link3,'Parent',h_axes, 'Xdata',[positions(1,2) positions(1,3)], ...
                                   'Ydata',[positions(2,2) positions(2,3)], ...
                                   'Zdata',[positions(3,2) positions(3,3)],'visible','on');
        set(link4,'Parent',h_axes, 'Xdata',[positions(1,3) positions(1,4)], ...
                                   'Ydata',[positions(2,3) positions(2,4)], ...
                                   'Zdata',[positions(3,3) positions(3,4)],'visible','on');
        set(link5,'Parent',h_axes, 'Xdata',[positions(1,4) positions(1,5)], ...
                                   'Ydata',[positions(2,4) positions(2,5)], ...
                                   'Zdata',[positions(3,4) positions(3,5)],'visible','on');
    elseif length(linkLengths)==6
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
        set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                                   'Ydata',[positions(2,1) positions(2,2)], ...
                                   'Zdata',[positions(3,1) positions(3,2)],'visible','on');    
        set(link3,'Parent',h_axes, 'Xdata',[positions(1,2) positions(1,3)], ...
                                   'Ydata',[positions(2,2) positions(2,3)], ...
                                   'Zdata',[positions(3,2) positions(3,3)],'visible','on');
        set(link4,'Parent',h_axes, 'Xdata',[positions(1,3) positions(1,4)], ...
                                   'Ydata',[positions(2,3) positions(2,4)], ...
                                   'Zdata',[positions(3,3) positions(3,4)],'visible','on');
        set(link5,'Parent',h_axes, 'Xdata',[positions(1,4) positions(1,5)], ...
                                   'Ydata',[positions(2,4) positions(2,5)], ...
                                   'Zdata',[positions(3,4) positions(3,5)],'visible','on');
        set(link6,'Parent',h_axes, 'Xdata',[positions(1,5) positions(1,6)], ...
                                   'Ydata',[positions(2,5) positions(2,6)], ...
                                   'Zdata',[positions(3,5) positions(3,6)],'visible','on');
    elseif length(linkLengths)==7   
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
        set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                                   'Ydata',[positions(2,1) positions(2,2)], ...
                                   'Zdata',[positions(3,1) positions(3,2)],'visible','on');    
        set(link3,'Parent',h_axes, 'Xdata',[positions(1,2) positions(1,3)], ...
                                   'Ydata',[positions(2,2) positions(2,3)], ...
                                   'Zdata',[positions(3,2) positions(3,3)],'visible','on');
        set(link4,'Parent',h_axes, 'Xdata',[positions(1,3) positions(1,4)], ...
                                   'Ydata',[positions(2,3) positions(2,4)], ...
                                   'Zdata',[positions(3,3) positions(3,4)],'visible','on');
        set(link5,'Parent',h_axes, 'Xdata',[positions(1,4) positions(1,5)], ...
                                   'Ydata',[positions(2,4) positions(2,5)], ...
                                   'Zdata',[positions(3,4) positions(3,5)],'visible','on');
        set(link6,'Parent',h_axes, 'Xdata',[positions(1,5) positions(1,6)], ...
                                   'Ydata',[positions(2,5) positions(2,6)], ...
                                   'Zdata',[positions(3,5) positions(3,6)],'visible','on');
        set(link7,'Parent',h_axes, 'Xdata',[positions(1,6) positions(1,7)], ...
                                   'Ydata',[positions(2,6) positions(2,7)], ...
                                   'Zdata',[positions(3,6) positions(3,7)],'visible','on');
    elseif length(linkLengths)==8
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
        set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                                   'Ydata',[positions(2,1) positions(2,2)], ...
                                   'Zdata',[positions(3,1) positions(3,2)],'visible','on');    
        set(link3,'Parent',h_axes, 'Xdata',[positions(1,2) positions(1,3)], ...
                                   'Ydata',[positions(2,2) positions(2,3)], ...
                                   'Zdata',[positions(3,2) positions(3,3)],'visible','on');
        set(link4,'Parent',h_axes, 'Xdata',[positions(1,3) positions(1,4)], ...
                                   'Ydata',[positions(2,3) positions(2,4)], ...
                                   'Zdata',[positions(3,3) positions(3,4)],'visible','on');
        set(link5,'Parent',h_axes, 'Xdata',[positions(1,4) positions(1,5)], ...
                                   'Ydata',[positions(2,4) positions(2,5)], ...
                                   'Zdata',[positions(3,4) positions(3,5)],'visible','on');
        set(link6,'Parent',h_axes, 'Xdata',[positions(1,5) positions(1,6)], ...
                                   'Ydata',[positions(2,5) positions(2,6)], ...
                                   'Zdata',[positions(3,5) positions(3,6)],'visible','on');
        set(link7,'Parent',h_axes, 'Xdata',[positions(1,6) positions(1,7)], ...
                                   'Ydata',[positions(2,6) positions(2,7)], ...
                                   'Zdata',[positions(3,6) positions(3,7)],'visible','on');
        set(link8,'Parent',h_axes, 'Xdata',[positions(1,7) positions(1,8)], ...
                                   'Ydata',[positions(2,7) positions(2,8)], ...
                                   'Zdata',[positions(3,7) positions(3,8)],'visible','on');
    elseif length(linkLengths)==9
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
        set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                                   'Ydata',[positions(2,1) positions(2,2)], ...
                                   'Zdata',[positions(3,1) positions(3,2)],'visible','on');    
        set(link3,'Parent',h_axes, 'Xdata',[positions(1,2) positions(1,3)], ...
                                   'Ydata',[positions(2,2) positions(2,3)], ...
                                   'Zdata',[positions(3,2) positions(3,3)],'visible','on');
        set(link4,'Parent',h_axes, 'Xdata',[positions(1,3) positions(1,4)], ...
                                   'Ydata',[positions(2,3) positions(2,4)], ...
                                   'Zdata',[positions(3,3) positions(3,4)],'visible','on');
        set(link5,'Parent',h_axes, 'Xdata',[positions(1,4) positions(1,5)], ...
                                   'Ydata',[positions(2,4) positions(2,5)], ...
                                   'Zdata',[positions(3,4) positions(3,5)],'visible','on');
        set(link6,'Parent',h_axes, 'Xdata',[positions(1,5) positions(1,6)], ...
                                   'Ydata',[positions(2,5) positions(2,6)], ...
                                   'Zdata',[positions(3,5) positions(3,6)],'visible','on');
        set(link7,'Parent',h_axes, 'Xdata',[positions(1,6) positions(1,7)], ...
                                   'Ydata',[positions(2,6) positions(2,7)], ...
                                   'Zdata',[positions(3,6) positions(3,7)],'visible','on');
        set(link8,'Parent',h_axes, 'Xdata',[positions(1,7) positions(1,8)], ...
                                   'Ydata',[positions(2,7) positions(2,8)], ...
                                   'Zdata',[positions(3,7) positions(3,8)],'visible','on');
        set(link9,'Parent',h_axes, 'Xdata',[positions(1,8) positions(1,9)], ...
                                   'Ydata',[positions(2,8) positions(2,9)], ...
                                   'Zdata',[positions(3,8) positions(3,9)],'visible','on');
    elseif length(linkLengths)==10
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
        set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                                   'Ydata',[positions(2,1) positions(2,2)], ...
                                   'Zdata',[positions(3,1) positions(3,2)],'visible','on');    
        set(link3,'Parent',h_axes, 'Xdata',[positions(1,2) positions(1,3)], ...
                                   'Ydata',[positions(2,2) positions(2,3)], ...
                                   'Zdata',[positions(3,2) positions(3,3)],'visible','on');
        set(link4,'Parent',h_axes, 'Xdata',[positions(1,3) positions(1,4)], ...
                                   'Ydata',[positions(2,3) positions(2,4)], ...
                                   'Zdata',[positions(3,3) positions(3,4)],'visible','on');
        set(link5,'Parent',h_axes, 'Xdata',[positions(1,4) positions(1,5)], ...
                                   'Ydata',[positions(2,4) positions(2,5)], ...
                                   'Zdata',[positions(3,4) positions(3,5)],'visible','on');
        set(link6,'Parent',h_axes, 'Xdata',[positions(1,5) positions(1,6)], ...
                                   'Ydata',[positions(2,5) positions(2,6)], ...
                                   'Zdata',[positions(3,5) positions(3,6)],'visible','on');
        set(link7,'Parent',h_axes, 'Xdata',[positions(1,6) positions(1,7)], ...
                                   'Ydata',[positions(2,6) positions(2,7)], ...
                                   'Zdata',[positions(3,6) positions(3,7)],'visible','on');
        set(link8,'Parent',h_axes, 'Xdata',[positions(1,7) positions(1,8)], ...
                                   'Ydata',[positions(2,7) positions(2,8)], ...
                                   'Zdata',[positions(3,7) positions(3,8)],'visible','on');
        set(link9,'Parent',h_axes, 'Xdata',[positions(1,8) positions(1,9)], ...
                                   'Ydata',[positions(2,8) positions(2,9)], ...
                                   'Zdata',[positions(3,8) positions(3,9)],'visible','on');
        set(link10,'Parent',h_axes,'Xdata',[positions(1,9) positions(1,10)], ...
                                   'Ydata',[positions(2,9) positions(2,10)], ...
                                   'Zdata',[positions(3,9) positions(3,10)],'visible','on');
    end                 
    set(targetVisual,'Parent',h_axes,'Xdata',[target(1)-0.01 target(1)+0.01], ...
                                     'Ydata',[target(2)-0.01 target(2)+0.01], ...
                                     'Zdata',[target(3)-0.01 target(3)+0.01],'visible','on');
    drawnow;
end