%% do forward kinematics of 7 link arm
function [pose, positions] = fk_cmaes(joints,linkLengths,target)
    global h_axes link1 link2 link3 link4 link5 link6 link7 link8 link9 link10 targetVisual;

    Tfinal = eye(4);
    
    %get complete Rotation Matrix
    for i=1:length(linkLengths)
        %rotation matrix for roll (Rx)
        Rx(:,:,i) = [1        0                      0       ; ...
                    0   cos(joints(i,1))    -sin(joints(i,1)); ...
                    0   sin(joints(i,1))     cos(joints(i,1))];
        
        %for pitch (Ry)
        Ry(:,:,i) = [cos(joints(i,2))   0    sin(joints(i,2)); ...
                    0                   1           0        ; ...
                    -sin(joints(i,2))   0    cos(joints(i,2))];
        
        %for yaw (Rz)  
        Rz(:,:,i) = [cos(joints(i,3))   -sin(joints(i,3))   0; ...
                    sin(joints(i,3))     cos(joints(i,3))   0; ...
                    0                        0              1];
       
        %overall rotation matrix
        R(:,:,i) = Rx(:,:,i)*Ry(:,:,i)*Rz(:,:,i);
        
        %homogeneous transformation matrix for one link
        Trot(:,:,i) = eye(4);
        Trot(1:3,1:3,i) = R(:,:,i);
        Ttrans(:,:,i) = eye(4);
        Ttrans(1,4,i) = linkLengths(i);
        T(:,:,i) = Trot(:,:,i)*Ttrans(:,:,i);
        
        %get complete transformation matrix
        Tfinal = Tfinal * T(:,:,i);
        positions(:,i) = Tfinal(1:3,4);
    end
    
    %get final pose
    Rfinal(:,:) = Tfinal(1:3,1:3);
    Qfinal = rotm2quat(Rfinal);
    Pfinal = positions(:,end)';
    finalPose = [Pfinal Qfinal];
    
    %draw all links
    if length(linkLengths)==1
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
    elseif length(linkLengths)==2
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
        set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                                   'Ydata',[positions(2,1) positions(2,2)], ...
                                   'Zdata',[positions(3,1) positions(3,2)],'visible','on');
    elseif length(linkLengths)==3
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
        set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                                   'Ydata',[positions(2,1) positions(2,2)], ...
                                   'Zdata',[positions(3,1) positions(3,2)],'visible','on');    
        set(link3,'Parent',h_axes, 'Xdata',[positions(1,2) positions(1,3)], ...
                                   'Ydata',[positions(2,2) positions(2,3)], ...
                                   'Zdata',[positions(3,2) positions(3,3)],'visible','on');
    elseif length(linkLengths)==4
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
        set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                                   'Ydata',[positions(2,1) positions(2,2)], ...
                                   'Zdata',[positions(3,1) positions(3,2)],'visible','on');    
        set(link3,'Parent',h_axes, 'Xdata',[positions(1,2) positions(1,3)], ...
                                   'Ydata',[positions(2,2) positions(2,3)], ...
                                   'Zdata',[positions(3,2) positions(3,3)],'visible','on');
        set(link4,'Parent',h_axes, 'Xdata',[positions(1,3) positions(1,4)], ...
                                   'Ydata',[positions(2,3) positions(2,4)], ...
                                   'Zdata',[positions(3,3) positions(3,4)],'visible','on');
    elseif length(linkLengths)==5
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
        set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                                   'Ydata',[positions(2,1) positions(2,2)], ...
                                   'Zdata',[positions(3,1) positions(3,2)],'visible','on');    
        set(link3,'Parent',h_axes, 'Xdata',[positions(1,2) positions(1,3)], ...
                                   'Ydata',[positions(2,2) positions(2,3)], ...
                                   'Zdata',[positions(3,2) positions(3,3)],'visible','on');
        set(link4,'Parent',h_axes, 'Xdata',[positions(1,3) positions(1,4)], ...
                                   'Ydata',[positions(2,3) positions(2,4)], ...
                                   'Zdata',[positions(3,3) positions(3,4)],'visible','on');
        set(link5,'Parent',h_axes, 'Xdata',[positions(1,4) positions(1,5)], ...
                                   'Ydata',[positions(2,4) positions(2,5)], ...
                                   'Zdata',[positions(3,4) positions(3,5)],'visible','on');
    elseif length(linkLengths)==6
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
        set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                                   'Ydata',[positions(2,1) positions(2,2)], ...
                                   'Zdata',[positions(3,1) positions(3,2)],'visible','on');    
        set(link3,'Parent',h_axes, 'Xdata',[positions(1,2) positions(1,3)], ...
                                   'Ydata',[positions(2,2) positions(2,3)], ...
                                   'Zdata',[positions(3,2) positions(3,3)],'visible','on');
        set(link4,'Parent',h_axes, 'Xdata',[positions(1,3) positions(1,4)], ...
                                   'Ydata',[positions(2,3) positions(2,4)], ...
                                   'Zdata',[positions(3,3) positions(3,4)],'visible','on');
        set(link5,'Parent',h_axes, 'Xdata',[positions(1,4) positions(1,5)], ...
                                   'Ydata',[positions(2,4) positions(2,5)], ...
                                   'Zdata',[positions(3,4) positions(3,5)],'visible','on');
        set(link6,'Parent',h_axes, 'Xdata',[positions(1,5) positions(1,6)], ...
                                   'Ydata',[positions(2,5) positions(2,6)], ...
                                   'Zdata',[positions(3,5) positions(3,6)],'visible','on');
    elseif length(linkLengths)==7   
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
        set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                                   'Ydata',[positions(2,1) positions(2,2)], ...
                                   'Zdata',[positions(3,1) positions(3,2)],'visible','on');    
        set(link3,'Parent',h_axes, 'Xdata',[positions(1,2) positions(1,3)], ...
                                   'Ydata',[positions(2,2) positions(2,3)], ...
                                   'Zdata',[positions(3,2) positions(3,3)],'visible','on');
        set(link4,'Parent',h_axes, 'Xdata',[positions(1,3) positions(1,4)], ...
                                   'Ydata',[positions(2,3) positions(2,4)], ...
                                   'Zdata',[positions(3,3) positions(3,4)],'visible','on');
        set(link5,'Parent',h_axes, 'Xdata',[positions(1,4) positions(1,5)], ...
                                   'Ydata',[positions(2,4) positions(2,5)], ...
                                   'Zdata',[positions(3,4) positions(3,5)],'visible','on');
        set(link6,'Parent',h_axes, 'Xdata',[positions(1,5) positions(1,6)], ...
                                   'Ydata',[positions(2,5) positions(2,6)], ...
                                   'Zdata',[positions(3,5) positions(3,6)],'visible','on');
        set(link7,'Parent',h_axes, 'Xdata',[positions(1,6) positions(1,7)], ...
                                   'Ydata',[positions(2,6) positions(2,7)], ...
                                   'Zdata',[positions(3,6) positions(3,7)],'visible','on');
    elseif length(linkLengths)==8
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
        set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                                   'Ydata',[positions(2,1) positions(2,2)], ...
                                   'Zdata',[positions(3,1) positions(3,2)],'visible','on');    
        set(link3,'Parent',h_axes, 'Xdata',[positions(1,2) positions(1,3)], ...
                                   'Ydata',[positions(2,2) positions(2,3)], ...
                                   'Zdata',[positions(3,2) positions(3,3)],'visible','on');
        set(link4,'Parent',h_axes, 'Xdata',[positions(1,3) positions(1,4)], ...
                                   'Ydata',[positions(2,3) positions(2,4)], ...
                                   'Zdata',[positions(3,3) positions(3,4)],'visible','on');
        set(link5,'Parent',h_axes, 'Xdata',[positions(1,4) positions(1,5)], ...
                                   'Ydata',[positions(2,4) positions(2,5)], ...
                                   'Zdata',[positions(3,4) positions(3,5)],'visible','on');
        set(link6,'Parent',h_axes, 'Xdata',[positions(1,5) positions(1,6)], ...
                                   'Ydata',[positions(2,5) positions(2,6)], ...
                                   'Zdata',[positions(3,5) positions(3,6)],'visible','on');
        set(link7,'Parent',h_axes, 'Xdata',[positions(1,6) positions(1,7)], ...
                                   'Ydata',[positions(2,6) positions(2,7)], ...
                                   'Zdata',[positions(3,6) positions(3,7)],'visible','on');
        set(link8,'Parent',h_axes, 'Xdata',[positions(1,7) positions(1,8)], ...
                                   'Ydata',[positions(2,7) positions(2,8)], ...
                                   'Zdata',[positions(3,7) positions(3,8)],'visible','on');
    elseif length(linkLengths)==9
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
        set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                                   'Ydata',[positions(2,1) positions(2,2)], ...
                                   'Zdata',[positions(3,1) positions(3,2)],'visible','on');    
        set(link3,'Parent',h_axes, 'Xdata',[positions(1,2) positions(1,3)], ...
                                   'Ydata',[positions(2,2) positions(2,3)], ...
                                   'Zdata',[positions(3,2) positions(3,3)],'visible','on');
        set(link4,'Parent',h_axes, 'Xdata',[positions(1,3) positions(1,4)], ...
                                   'Ydata',[positions(2,3) positions(2,4)], ...
                                   'Zdata',[positions(3,3) positions(3,4)],'visible','on');
        set(link5,'Parent',h_axes, 'Xdata',[positions(1,4) positions(1,5)], ...
                                   'Ydata',[positions(2,4) positions(2,5)], ...
                                   'Zdata',[positions(3,4) positions(3,5)],'visible','on');
        set(link6,'Parent',h_axes, 'Xdata',[positions(1,5) positions(1,6)], ...
                                   'Ydata',[positions(2,5) positions(2,6)], ...
                                   'Zdata',[positions(3,5) positions(3,6)],'visible','on');
        set(link7,'Parent',h_axes, 'Xdata',[positions(1,6) positions(1,7)], ...
                                   'Ydata',[positions(2,6) positions(2,7)], ...
                                   'Zdata',[positions(3,6) positions(3,7)],'visible','on');
        set(link8,'Parent',h_axes, 'Xdata',[positions(1,7) positions(1,8)], ...
                                   'Ydata',[positions(2,7) positions(2,8)], ...
                                   'Zdata',[positions(3,7) positions(3,8)],'visible','on');
        set(link9,'Parent',h_axes, 'Xdata',[positions(1,8) positions(1,9)], ...
                                   'Ydata',[positions(2,8) positions(2,9)], ...
                                   'Zdata',[positions(3,8) positions(3,9)],'visible','on');
    elseif length(linkLengths)==10
        set(link1,'Parent',h_axes, 'Xdata',[0              positions(1,1)], ...
                                   'Ydata',[0              positions(2,1)], ...
                                   'Zdata',[0              positions(3,1)],'visible','on');
        set(link2,'Parent',h_axes, 'Xdata',[positions(1,1) positions(1,2)], ...
                                   'Ydata',[positions(2,1) positions(2,2)], ...
                                   'Zdata',[positions(3,1) positions(3,2)],'visible','on');    
        set(link3,'Parent',h_axes, 'Xdata',[positions(1,2) positions(1,3)], ...
                                   'Ydata',[positions(2,2) positions(2,3)], ...
                                   'Zdata',[positions(3,2) positions(3,3)],'visible','on');
        set(link4,'Parent',h_axes, 'Xdata',[positions(1,3) positions(1,4)], ...
                                   'Ydata',[positions(2,3) positions(2,4)], ...
                                   'Zdata',[positions(3,3) positions(3,4)],'visible','on');
        set(link5,'Parent',h_axes, 'Xdata',[positions(1,4) positions(1,5)], ...
                                   'Ydata',[positions(2,4) positions(2,5)], ...
                                   'Zdata',[positions(3,4) positions(3,5)],'visible','on');
        set(link6,'Parent',h_axes, 'Xdata',[positions(1,5) positions(1,6)], ...
                                   'Ydata',[positions(2,5) positions(2,6)], ...
                                   'Zdata',[positions(3,5) positions(3,6)],'visible','on');
        set(link7,'Parent',h_axes, 'Xdata',[positions(1,6) positions(1,7)], ...
                                   'Ydata',[positions(2,6) positions(2,7)], ...
                                   'Zdata',[positions(3,6) positions(3,7)],'visible','on');
        set(link8,'Parent',h_axes, 'Xdata',[positions(1,7) positions(1,8)], ...
                                   'Ydata',[positions(2,7) positions(2,8)], ...
                                   'Zdata',[positions(3,7) positions(3,8)],'visible','on');
        set(link9,'Parent',h_axes, 'Xdata',[positions(1,8) positions(1,9)], ...
                                   'Ydata',[positions(2,8) positions(2,9)], ...
                                   'Zdata',[positions(3,8) positions(3,9)],'visible','on');
        set(link10,'Parent',h_axes,'Xdata',[positions(1,9) positions(1,10)], ...
                                   'Ydata',[positions(2,9) positions(2,10)], ...
                                   'Zdata',[positions(3,9) positions(3,10)],'visible','on');
    end                 
    set(targetVisual,'Parent',h_axes,'Xdata',[target(1)-0.01 target(1)+0.01], ...
                                     'Ydata',[target(2)-0.01 target(2)+0.01], ...
                                     'Zdata',[target(3)-0.01 target(3)+0.01],'visible','on');
    drawnow;
	pose = finalPose;
end